- name: homebrew taps
  homebrew_tap:
    tap: '{{ item }}'
  with_items: '{{ homebrew_taps }}'

- name: Update homebrew
  homebrew:
    name: git
    state: latest
    update_homebrew: yes
  tags:
    - brew

- name: Install Java
  homebrew_cask:
    name: 'java'
    state: installed
  tags:
    - brew

- name: Install homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items: "{{ lookup('file', 'homebrew_packages.txt').splitlines() }}"
  tags:
    - brew

- name: Install homebrew cask packages
  homebrew_cask:
    name: '{{ item }}'
    state: installed
  with_items: "{{ lookup('file', 'homebrew_cask_packages.txt').splitlines() }}"
  tags:
    - brew

- name: Install pip packages
  pip:
    name: '{{ item }}'
    state: latest
  with_items: "{{ lookup('file', 'pip_packages.txt').splitlines() }}"
  tags:
    - pip

- name: Install npm packages
  npm:
    name: '{{ item }}'
    state: latest
    global: yes
  with_items: "{{ lookup('file', 'npm_packages.txt').splitlines() }}"
  tags:
    - npm

- name: Install gem packages
  gem:
    name: '{{ item }}'
    state: latest
  with_items: "{{ lookup('file', 'gem_packages.txt').splitlines() }}"
  tags: [gem]
